<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Nullable>disable</Nullable>
        <PackageId>Qml.Net</PackageId>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>disable</ImplicitUsings>
        <NeutralLanguage>en-US</NeutralLanguage>
        <TargetFramework>netstandard2.0</TargetFramework>
        <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <WarningLevel>8</WarningLevel>
        <DebugType>embedded</DebugType>
        <DebugSymbols>true</DebugSymbols>

        <TrimMode>partial</TrimMode>
        <PublishRelease>true</PublishRelease>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishReadyToRun>true</PublishReadyToRun>

        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <NoWarn>1701;1702;IL2026</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="preload.linux.txt"/>
        <Content Include="preload.linux.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\net-native-lib-loader\src\NetNativeLibLoader\NetNativeLibLoader.csproj"/>
    </ItemGroup>
</Project>
